-- inventory ta 3 mah ayande expire mishavad...
-- :_)
-- kobi baby man Daniiiiiiiiiiii

Config = {}

Config.tintsIndex = {
    [1] = 'tintgreen',
    [2] = 'tintgold',
    [3] = 'tintpink',
    [6] = 'tintorange',
    [7] = 'tintplat'
}

BackItems = {
    [GetHashKey("weapon_microsmg")] = {
        model="w_sb_microsmg",
        back_bone = 24818,
        x = 0.115,
        y = -0.167,
        z = 0.1,
        x_rotation = 0.0,
        y_rotation = 0.0,
        z_rotation = 0.0,
    },
    [GetHashKey("weapon_smg")] = {
        model="w_sb_smg",
        back_bone = 24818,
        x = 0.115,
        y = -0.167,
        z = 0.1,
        x_rotation = 0.0,
        y_rotation = 0.0,
        z_rotation = 0.0,
    },
    [GetHashKey("weapon_smg_mk2")] = {
        model="w_sb_smgmk2",
        back_bone = 24818,
        x = 0.115,
        y = -0.167,
        z = 0.1,
        x_rotation = 0.0,
        y_rotation = 0.0,
        z_rotation = 0.0,
    },
    [GetHashKey("weapon_combatpdw")] = {
        model="w_sb_smgmk2",
        back_bone = 24818,
        x = 0.02,
        y = -0.167,
        z = 0.03,
        x_rotation = 0.0,
        y_rotation = 0.0,
        z_rotation = 0.0,
    },
    [GetHashKey("weapon_assaultrifle")] = {
        model="w_ar_assaultrifle",
        back_bone = 24818,
        x = 0.115,
        y = -0.167,
        z = 0.1,
        x_rotation = 0.0,
        y_rotation = 0.0,
        z_rotation = 0.0,
    },
    [GetHashKey("weapon_assaultrifle_mk2")] = {
        model="w_ar_assaultrifle",
        back_bone = 24818,
        x = 0.115,
        y = -0.167,
        z = 0.1,
        x_rotation = 0.0,
        y_rotation = 0.0,
        z_rotation = 0.0,
    },
    [GetHashKey("weapon_carbinerifle")] = {
        model="w_ar_carbinerifle",
        back_bone = 24818,
        x = 0.115,
        y = -0.167,
        z = 0.1,
        x_rotation = 0.0,
        y_rotation = 0.0,
        z_rotation = 0.0,
    },
    [GetHashKey("weapon_carbinerifle_mk2")] = {
        model="w_ar_carbineriflemk2",
        back_bone = 24818,
        x = 0.115,
        y = -0.167,
        z = 0.1,
        x_rotation = 0.0,
        y_rotation = 0.0,
        z_rotation = 0.0,
    },
    [GetHashKey("weapon_specialcarbine")] = {
        model="w_ar_specialcarbine",
        back_bone = 24818,
        x = 0.115,
        y = -0.167,
        z = 0.1,
        x_rotation = 0.0,
        y_rotation = 0.0,
        z_rotation = 0.0,
    },
    [GetHashKey("weapon_bullpuprifle")] = {
        model="w_ar_bullpuprifle",
        back_bone = 24818,
        x = 0.115,
        y = -0.167,
        z = 0.1,
        x_rotation = 0.0,
        y_rotation = 0.0,
        z_rotation = 0.0,
    },
    [GetHashKey("weapon_specialcarbine_mk2")] = {
        model="w_ar_specialcarbine",
        back_bone = 24818,
        x = 0.115,
        y = -0.167,
        z = 0.1,
        x_rotation = 0.0,
        y_rotation = 0.0,
        z_rotation = 0.0,
    },
    [GetHashKey("weapon_bullpuprifle_mk2")] = {
        model="w_ar_bullpuprifle",
        back_bone = 24818,
        x = 0.115,
        y = -0.167,
        z = 0.1,
        x_rotation = 0.0,
        y_rotation = 0.0,
        z_rotation = 0.0,
    },
    [GetHashKey("weapon_advancedrifle")] = {
        model="w_ar_advancedrifle",
        back_bone = 24818,
        x = 0.34,
        y = -0.167,
        z = 0.1,
        x_rotation = 0.0,
        y_rotation = 0.0,
        z_rotation = 0.0,
    },
    [GetHashKey("weapon_mg")] = {
        model="w_mg_mg",
        back_bone = 24818,
        x = 0.115,
        y = -0.167,
        z = 0.1,
        x_rotation = 0.0,
        y_rotation = 0.0,
        z_rotation = 0.0,
    },
    [GetHashKey("weapon_combatmg")] = {
        model="w_mg_combatmg",
        back_bone = 24818,
        x = 0.115,
        y = -0.167,
        z = 0.1,
        x_rotation = 0.0,
        y_rotation = 0.0,
        z_rotation = 0.0,
    },
    [GetHashKey("weapon_gusenberg")] = {
        model="w_sb_gusenberg",
        back_bone = 24818,
        x = 0.115,
        y = -0.167,
        z = 0.1,
        x_rotation = 0.0,
        y_rotation = 0.0,
        z_rotation = 0.0,
    },
    [GetHashKey("weapon_bat")] = {
        model="w_me_bat",
        back_bone = 24818,
        x = 0.45,
        y = -0.15,
        z = -0.21,
        x_rotation = 0.0,
        y_rotation = 60.0,
        z_rotation = -180.0,
    },
    [GetHashKey("weapon_pumpshotgun")] = {
        model="w_sg_pumpshotgun",
        back_bone = 24818,
        x = -0.1,
        y = -0.167,
        z = 0.1,
        x_rotation = 0.0,
        y_rotation = 0.0,
        z_rotation = 0.0,
    },
    [GetHashKey("weapon_pumpshotgun_mk2")] = {
        model="w_sg_pumpshotgunmk2",
        back_bone = 24818,
        x = 0.115,
        y = -0.167,
        z = 0.1,
        x_rotation = 0.0,
        y_rotation = 0.0,
        z_rotation = 0.0,
    },
    [GetHashKey("weapon_bullpupshotgun")] = {
        model="w_sg_bullpupshotgun",
        back_bone = 24818,
        x = 0.115,
        y = -0.167,
        z = 0.1,
        x_rotation = 0.0,
        y_rotation = 0.0,
        z_rotation = 0.0,
    },
    [GetHashKey("weapon_assaultshotgun")] = {
        model="w_sg_assaultshotgun",
        back_bone = 24818,
        x = 0.115,
        y = -0.167,
        z = 0.1,
        x_rotation = 0.0,
        y_rotation = 0.0,
        z_rotation = 0.0,
    },
    [GetHashKey("weapon_heavyshotgun")] = {
        model="w_sg_heavyshotgun",
        back_bone = 24818,
        x = 0.115,
        y = -0.167,
        z = 0.1,
        x_rotation = 0.0,
        y_rotation = 0.0,
        z_rotation = 0.0,
    },
    [GetHashKey("weapon_sniperrifle")] = {
        model="w_sr_sniperrifle2",
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 0.0,
        z_rotation = 0.0,
    },
    [GetHashKey("weapon_heavysniper")] = {
        model="w_sr_heavysniper",
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 0.0,
        z_rotation = 0.0,
    },
    [GetHashKey("weapon_rpg")] = {
        model="w_lr_rpg",
        back_bone = 24818,
        x = 0.5,
        y = -0.17,
        z = 0.09,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
}

Config.Objects = {
	['weapon_assaultrifle'] = 'w_ar_assaultrifle',
	['weapon_snspistol'] = 'w_pi_sns_pistol',
	['weapon_pistol50'] = 'w_pi_pistol50',
	['weapon_pistol'] = 'w_pi_pistol',
	['weapon_heavypistol'] = 'w_pi_heavypistol',
	['weapon_smg'] = 'w_sb_smg',
	['weapon_bat'] = 'w_me_bat',
	['weapon_nightstick'] = 'w_me_nightstick',
	['weapon_carbinerifle'] = 'w_ar_carbinerifle',
    ['weapon_advancedrifle'] = 'w_ar_advancedrifle',
    ['weapon_microsmg'] = 'w_sb_microsmg',
    ['weapon_assaultsmg'] = 'w_sb_assaultsmg',
    ['weapon_appistol'] = 'w_pi_appistol',
    ['weapon_combatpistol'] = 'w_pi_combatpistol',
    ['weapon_specialcarbine'] = 'w_ar_specialcarbine',
    ['weapon_stungun'] = 'w_pi_stungun',
    ['weapon_pumpshotgun'] = 'w_sg_pumpshotgun',
    ['weapon_musket'] = 'w_ar_musket',
    ['weapon_bullpuprifle'] = 'w_ar_bullpuprifle',
    ['weapon_gusenberg'] = 'w_sb_gusenberg',
    ['weapon_sniperrifle'] = 'w_sr_sniperrifle',
    ['weapon_heavysniper'] = 'w_sr_heavysniper',
	['weapon_knife'] = 'w_me_knife_01',
	['radio'] = 'prop_cs_hand_radio',
	['phone'] = 'prop_player_phone_01',
    ['bag'] = 'prop_big_bag_01',
}
