-- This can be access like:
-- exports['lls-mechanic'].openMenuByAdmin()
-- after that the menu will open with all prices to 0 at any position
-- exports('openMenuByAdmin', function()
--     isOpenByAdmin = true
--     openUI()
-- end)
