ESX.Items = {
	["radio"] = {name = "radio", label = "Radio", weight = 1, unique = true, usable = false, type = 'item_standard', eligableIndex = 5},
	["5.56mm"] = {name = "5.56mm", label = "5.56mm", weight = 0.01, unique = false, usable = false, type = 'item_ammo'},
	["7.62mm"] = {name = "7.62mm", label = "7.62mm", weight = 0.01, unique = false, usable = false, type = 'item_ammo'},
	["9mm"] = {name = "9mm", label = "9mm", weight = 0.01, unique = false, usable = false, type = 'item_ammo'},
	["12_gauge"] = {name = "12_gauge", label = "12_gauge", weight = 0.01, unique = false, usable = false, type = 'item_ammo'},
	["25_acp"] = {name = "25_acp", label = "25_acp", weight = 0.01, unique = false, usable = false, type = 'item_ammo'},
	["32_acp"] = {name = "32_acp", label = "32_acp", weight = 0.01, unique = false, usable = false, type = 'item_ammo'},
	["44_magnum"] = {name = "44_magnum", label = "44_magnum", weight = 0.01, unique = false, usable = false, type = 'item_ammo'},
	["45_acp"] = {name = "45_acp", label = "45_acp", weight = 0.01, unique = false, usable = false, type = 'item_ammo'},
	["50mm_bmg"] = {name = "50mm_bmg", label = "50mm_bmg", weight = 0.01, unique = false, usable = false, type = 'item_ammo'},
	["54r"] = {name = "54r", label = "54r", weight = 0.01, unique = false, usable = false, type = 'item_ammo'},
	["clip_extended"] = {name = "clip_extended", label = "Extended Clip", weight = 2, unique = false, usable = false, type = 'item_attachment'},
	["clip_drum"] = {name = "clip_drum", label = "Drum Clip", weight = 2, unique = false, usable = false, type = 'item_attachment'},
	["flashlight"] = {name = "flashlight", label = "Flashlight", weight = 1, unique = false, usable = false, type = 'item_attachment'},
	["suppressor"] = {name = "suppressor", label = "Silencer", weight = 1, unique = false, usable = false, type = 'item_attachment'},
	["scope"] = {name = "scope", label = "Scope", weight = 1, unique = false, usable = false, type = 'item_attachment'},
	["grip"] = {name = "grip", label = "Grip", weight = 1, unique = false, usable = false, type = 'item_attachment'},
	["tintgold"] = {name = "tintgold", label = "Gold Tint", weight = 1, unique = false, usable = false, type = 'item_tint'},
	["tintgreen"] = {name = "tintgreen", label = "Green Tint", weight = 1, unique = false, usable = false, type = 'item_tint'},
	["tintorange"] = {name = "tintorange", label = "Orange Tint", weight = 1, unique = false, usable = false, type = 'item_tint'},
	["tintpink"] = {name = "tintpink", label = "Pink Tint", weight = 1, unique = false, usable = false, type = 'item_tint'},
	["tintplat"] = {name = "tintplat", label = "Platinum Tint", weight = 1, unique = false, usable = false, type = 'item_tint'},
	["bag"] = {name = "bag", label = "Bag", weight = 10, unique = true, usable = false, type = 'item_standard', canPickup = true},
	["mask"] = {name = "mask", label = "Mask", weight = 1, unique = true, usable = false, type = 'item_standard', eligableIndex = 7},
	---------------------------------
	["classic_phone"] = {name = "classic_phone", label = "Classic Phone", weight = 1, unique = true, usable = false, type = 'item_standard', eligableIndex = 6},
	["black_phone"] = {name = "black_phone", label = "Black Phone", weight = 1, unique = true, usable = false, type = 'item_standard', eligableIndex = 6},
	["blue_phone"] = {name = "blue_phone", label = "Blue Phone", weight = 1, unique = true, usable = false, type = 'item_standard', eligableIndex = 6},
	["gold_phone"] = {name = "gold_phone", label = "Gold Phone", weight = 1, unique = true, usable = false, type = 'item_standard', eligableIndex = 6},
	["red_phone"] = {name = "red_phone", label = "Red Phone", weight = 1, unique = true, usable = false, type = 'item_standard', eligableIndex = 6},
	["green_phone"] = {name = "green_phone", label = "Green Phone", weight = 1, unique = true, usable = false, type = 'item_standard', eligableIndex = 6},
	["greenlight_phone"] = {name = "greenlight_phone", label = "Green Light Phone", weight = 1, unique = true, usable = false, type = 'item_standard', eligableIndex = 6},
	["pink_phone"] = {name = "pink_phone", label = "Pink Phone", weight = 1, unique = true, usable = false, type = 'item_standard', eligableIndex = 6},
	["white_phone"] = {name = "white_phone", label = "White Phone", weight = 1, unique = true, usable = false, type = 'item_standard', eligableIndex = 6},
	["wet_classic_phone"] = {name = "wet_classic_phone", label = "Wet Classic Phone", weight = 1, unique = true, usable = false, type = 'item_standard'},
	["wet_black_phone"] = {name = "wet_black_phone", label = "Wet Black Phone", weight = 1, unique = true, usable = false, type = 'item_standard'},
	["wet_blue_phone"] = {name = "wet_blue_phone", label = "Wet Blue Phone", weight = 1, unique = true, usable = false, type = 'item_standard'},
	["wet_gold_phone"] = {name = "wet_gold_phone", label = "Wet Gold Phone", weight = 1, unique = true, usable = false, type = 'item_standard'},
	["wet_red_phone"] = {name = "wet_red_phone", label = "Wet Red Phone", weight = 1, unique = true, usable = false, type = 'item_standard'},
	["wet_green_phone"] = {name = "wet_green_phone", label = "Wet Green Phone", weight = 1, unique = true, usable = false, type = 'item_standard'},
	["wet_greenlight_phone"] = {name = "wet_greenlight_phone", label = "Wet Green Light Phone", weight = 1, unique = true, usable = false, type = 'item_standard'},
	["wet_pink_phone"] = {name = "wet_pink_phone", label = "Wet Pink Phone", weight = 1, unique = true, usable = false, type = 'item_standard'},
	["wet_white_phone"] = {name = "wet_white_phone", label = "Wet White Phone", weight = 1, unique = true, usable = false, type = 'item_standard'},
	["phone_hack"] = {name = "phone_hack", label = "Phone Hack", weight = 0.3, unique = true, usable = false, type = 'item_standard'},
	["phone_module"] = {name = "phone_module", label = "Phone Module", weight = 0.5, unique = true, usable = false, type = 'item_standard'},
	["powerbank"] = {name = "powerbank", label = "Power Bank", weight = 3, unique = true, usable = false, type = 'item_standard'},
	--------------------------------- *
	["bodycam"] = {name = "bodycam", label = "Body Cam", weight = 0.5, unique = false, usable = true, type = 'item_standard'},
	["megaphone"] = {name = "megaphone", label = "Megaphone", weight = 1, unique = true, usable = true, type = 'item_standard'},
	["handcuff"] = {name = "handcuff", label = "Handcuff", weight = 0.3, unique = false, usable = false, type = 'item_standard'},
	["idcard"] = {name = "idcard", label = "ID Card", weight = 0.1, unique = false, usable = true, type = 'item_standard'},
	["+age"] = {name = "bandage", label = "Bandage", weight = 0.5, unique = false, usable = true, type = 'item_standard'},
	["Medkit"] = {name = "Medkit", label = "ifak", weight = 1.5, unique = false, usable = true, type = 'item_standard'},
	["painkiller"] = {name = "painkiller", label = "Pain Killer", weight = 0.5, unique = false, usable = true, type = 'item_standard'}, -- 	Added ghorsi ke arom arom heal mide
	["fixkit"] = {name = "fixkit", label = "Repair kit", weight = 2.5, unique = false, usable = true, type = 'item_standard'},
	["carokit"] = {name = "carokit", label = "Body Repair Kit", weight = 4.5, unique = false, usable = true, type = 'item_standard'},
	["bread"] = {name = "bread", label = "Bread", weight = 0.4, unique = false, usable = true, type = 'item_standard'},
	["gps"] = {name = "gps", label = "Gps", weight = 0.3, unique = false, usable = true, type = 'item_standard'},
	["pizza"] = {name = "pizza", label = "Pizza", weight = 0.7, unique = false, usable = true, type = 'item_standard'},
	["lighter"] = {name = "lighter", label = "Lighter", weight = 0.1, unique = false, usable = true, type = 'item_standard'},
	["copper"] = {name = "copper", label = "Copper", weight = 1, unique = false, usable = true, type = 'item_standard'},
	["stone"] = {name = "stone", label = "Stone", weight = 0.3, unique = false, usable = true, type = 'item_standard'},
	["washed_stone"] = {name = "washed_stone", label = "Washed stone", weight = 0.3, unique = false, usable = true, type = 'item_standard'},
	["iron"] = {name = "iron", label = "Iron", weight = 0.4, unique = false, usable = true, type = 'item_standard'},
	["gold"] = {name = "gold", label = "Gold", weight = 0.3, unique = false, usable = true, type = 'item_standard'},
	["diamond"] = {name = "diamond", label = "Diamond", weight = 0.3, unique = false, usable = true, type = 'item_standard'},
	["blowtorch"] = {name = "blowtorch", label = "Blowtorch", weight = 1, unique = false, usable = true, type = 'item_standard'},
	["drill"] = {name = "drill", label = "Drill", weight = 2.5, unique = false, usable = true, type = 'item_standard'},
	["picklock"] = {name = "picklock", label = "Pick Lock", weight = 0.6, unique = false, usable = true, type = 'item_standard'},
	["yusuf"] = {name = "yusuf", label = "Gold Skin", weight = 0.1, unique = false, usable = true, type = 'item_standard'},
	["goldfish"] = {name = "goldfish", label = "Gold Fish", weight = 0.2, unique = false, usable = true, type = 'item_standard'},
	["ghezelala"] = {name = "ghezelala", label = "Trout Fish", weight = 1, unique = false, usable = true, type = 'item_standard'},
	["hamoor"] = {name = "hamoor", label = "Grouper fish", weight = 0.9, unique = false, usable = true, type = 'item_standard'},
	["salomon"] = {name = "salomon", label = "Salomon", weight = 0.7, unique = false, usable = true, type = 'item_standard'},
	["dampaii"] = {name = "dampaii", label = "Slipper", weight = 0.3, unique = false, usable = true, type = 'item_standard'},
	["meygoo"] = {name = "meygoo", label = "Shrimp", weight = 0.1, unique = false, usable = true, type = 'item_standard'},
	["fanta"] = {name = "fanta", label = "Fanta", weight = 0.7, unique = false, usable = true, type = 'item_standard'},
	["sprite"] = {name = "sprite", label = "Sprite", weight = 0.5, unique = false, usable = true, type = 'item_standard'},
	["loka"] = {name = "loka", label = "Loka", weight = 0.5, unique = false, usable = true, type = 'item_standard'},
	["cheesebows"] = {name = "cheesebows", label = "Snack", weight = 0.6, unique = false, usable = true, type = 'item_standard'},
	["chips"] = {name = "chips", label = "Chips", weight = 0.5, unique = false, usable = true, type = 'item_standard'},
	["marabou"] = {name = "marabou", label = "Chocolate", weight = 0.3, unique = false, usable = true, type = 'item_standard'},
	["burger"] = {name = "burger", label = "Burger", weight = 0.75, unique = false, usable = true, type = 'item_standard'},
	["macka"] = {name = "macka", label = "Pasta", weight = 1, unique = false, usable = true, type = 'item_standard'},
	["lotteryticket"] = {name = "lotteryticket", label = "lottery ticket", weight = 0.1, unique = false, usable = true, type = 'item_standard'},
	["soda"] = {name = "soda", label = "Soda pop", weight = 0.4, unique = false, usable = true, type = 'item_standard'},
	["coffee"] = {name = "coffee", label = "Coffee", weight = 0.8, unique = false, usable = true, type = 'item_standard'},
	["tea"] = {name = "tea", label = "Tea", weight = 0.6, unique = false, usable = true, type = 'item_standard'},
	["donut"] = {name = "donut", label = "Donut", weight = 0.4, unique = false, usable = true, type = 'item_standard'},
	["whiskey"] = {name = "whiskey", label = "Whiskey", weight = 1, unique = false, usable = true, type = 'item_standard'},
	["wine"] = {name = "wine", label = "Wine", weight = 1, unique = false, usable = true, type = 'item_standard'},
	["beer"] = {name = "beer", label = "Beer", weight = 1, unique = false, usable = true, type = 'item_standard'},
	["sandwich"] = {name = "sandwich", label = "Sandwich", weight = 0.5, unique = false, usable = true, type = 'item_standard'},
	["cigar"] = {name = "cigar", label = "Cigar", weight = 0.3, unique = false, usable = true, type = 'item_standard'},
	["armor50"] = {name = "armor50", label = "Armor[50]", weight =3.5, unique = false, usable = true, type = 'item_standard'},
	["armor75"] = {name = "armor75", label = "Armor[75]", weight = 4.5, unique = false, usable = true, type = 'item_standard'},
	["armor100"] = {name = "armor100", label = "Heavy Armor", weight = 5.5, unique = false, usable = true, type = 'item_standard'},
	["net_cracker"] = {name = "net_cracker", label = "Net Cracker", weight = 0.4, unique = false, usable = true, type = 'item_standard'},
	["thermite"] = {name = "thermite", label = "Thermite Bomb", weight = 1.5, unique = false, usable = true, type = 'item_standard'},
	-- ["condom"] = {name = "condom", label = "Condom Khardar", weight = 0.3, unique = false, usable = true, type = 'item_standard'},
	-- ["levonorgestrel"] = {name = "levonorgestrel", label = "Ghors Emergency", weight = 0.3, unique = false, usable = true, type = 'item_standard'},
	-- ["mifepristone"] = {name = "mifepristone", label = "Mifepristone", weight = 0.3, unique = false, usable = true, type = 'item_standard'},
	-- ["testpack"] = {name = "testpack", label = "Baby Check", weight = 0.3, unique = false, usable = true, type = 'item_standard'},
	-- ["viagra"] = {name = "viagra", label = "Taghviyat Jensi", weight = 0.3, unique = false, usable = true, type = 'item_standard'},
	["jewelry"] = {name = "jewelry", label = "Javaher", weight = 0.3, unique = false, usable = true, type = 'item_standard'},
	["rolex"] = {name = "rolex", label = "Rolex", weight = 0.3, unique = false, usable = true, type = 'item_standard'},
	["ring"] = {name = "ring", label = "Ring", weight = 0.3, unique = false, usable = true, type = 'item_standard'},
	["necklace"] = {name = "necklace", label = "Necklaces", weight = 0.3, unique = false, usable = true, type = 'item_standard'},
	["painting"] = {name = "tablo", label = "Board", weight = 0.3, unique = false, usable = true, type = 'item_standard'},
	["c4_bomb"] = {name = "c4_bomb", label = "C4", weight = 0.3, unique = false, usable = true, type = 'item_standard'},
	["thermite"] = {name = "thermite", label = "Bomb Thermite", weight = 0.3, unique = false, usable = true, type = 'item_standard'},
	["laptop"] = {name = "laptop", label = "Laptop", weight = 2, unique = false, usable = true, type = 'item_standard'},
	["hack_usb"] = {name = "hack_usb", label = "Usb hack", weight = 0.2, unique = false, usable = true, type = 'item_standard'},
	["platinum"] = {name = "platinum", label = "Platinum", weight = 0.4, unique = false, usable = true, type = 'item_standard'},
	["oil"] = {name = "oil", label = "Oil barrel", weight = 6, unique = false, usable = true, type = 'item_standard'},
	["enginelevel1"] = {name = "enginelevel1", label = "Engine LV 1", weight = 20, unique = false, usable = true, type = 'item_standard'},
	["enginelevel2"] = {name = "enginelevel2", label = "Engine LV 2", weight = 20, unique = false, usable = true, type = 'item_standard'},
	["enginelevel3"] = {name = "enginelevel3", label = "Engine LV 3", weight = 20, unique = false, usable = true, type = 'item_standard'},
	["enginelevel4"] = {name = "enginelevel4", label = "Engine LV 4", weight = 20, unique = false, usable = true, type = 'item_standard'},
	["turbolevel1"] = {name = "turbolevel1", label = "Turbo LV 1", weight = 5, unique = false, usable = true, type = 'item_standard'},
	["turbolevel2"] = {name = "turbolevel2", label = "Turbo LV 2", weight = 5, unique = false, usable = true, type = 'item_standard'},
	["suspensionlevel1"] = {name = "suspensionlevel1", label = "Suspension LV 1", weight = 10, unique = false, usable = true, type = 'item_standard'},
	["suspensionlevel2"] = {name = "suspensionlevel2", label = "Suspension LV 2", weight = 10, unique = false, usable = true, type = 'item_standard'},
	["suspensionlevel3"] = {name = "suspensionlevel3", label = "Suspension Lv 3", weight = 10, unique = false, usable = true, type = 'item_standard'},
	["transmissionlevel1"] = {name = "transmissionlevel1", label = "Transmission LV 1", weight = 20, unique = false, usable = true, type = 'item_standard'},
	["transmissionlevel2"] = {name = "transmissionlevel2", label = "Transmission LV 2", weight = 20, unique = false, usable = true, type = 'item_standard'},
	["transmissionlevel3"] = {name = "transmissionlevel3", label = "Transmission LV 3", weight = 20, unique = false, usable = true, type = 'item_standard'},
	["transmissionlevel4"] = {name = "transmissionlevel4", label = "Transmission LV 4", weight = 20, unique = false, usable = true, type = 'item_standard'},
	--itemUwUCafe--Create
	["cleaner"] = {name = "cleaner", label = "Cleaner", weight = 0.1, unique = false, usable = false, type = 'item_standard'},
	["pacote-leite"] = {name = "pacote-leite", label = "Milk pack", weight = 1, unique = false, usable = false, type = 'item_standard'},
	["barra-manteiga"] = {name = "barra-manteiga", label = "Butter bar", weight = 0.5, unique = false, usable = false, type = 'item_standard'},
	["pacote-farinha"] = {name = "pacote-farinha", label = "Flour package", weight = 0.7, unique = false, usable = false, type = 'item_standard'},
	["barra-chocolate"] = {name = "barra-chocolate", label = "Chocolate bar", weight = 0.2, unique = false, usable = false, type = 'item_standard'},
	["caixa-morangos"] = {name = "caixa-morangos", label = "Box of strawberries", weight = 0.8, unique = false, usable = false, type = 'item_standard'},
	["limao"] = {name = "limao", label = "Lemon", weight = 0.1, unique = false, usable = false, type = 'item_standard'},
	["pacote-natas"] = {name = "pacote-natas", label = "Package of cream", weight = 0.4, unique = false, usable = false, type = 'item_standard'},
	["leite-condensado"] = {name = "leite-condensado", label = "Condensed milk", weight = 1, unique = false, usable = false, type = 'item_standard'},			
	["extrato-baunilha"] = {name = "extrato-baunilha", label = "Vanilla extract", weight = 0.5, unique = false, usable = false, type = 'item_standard'},
	["pacote-acucar"] = {name = "pacote-acucar", label = "Suger pack", weight = 0.6, unique = false, usable = false, type = 'item_standard'},
	["frasco-nutela"] = {name = "frasco-nutela", label = "Jar of Nutella", weight = 0.7, unique = false, usable = false, type = 'item_standard'},
	["pacote-oreo"] = {name = "pacote-oreo", label = "Oreo pack", weight = 0.4, unique = false, usable = false, type = 'item_standard'},
	["extrato-menta"] = {name = "extrato-menta", label = "Mint extract", weight = 20, unique = false, usable = false, type = 'item_standard'},
	["caixa-amoras"] = {name = "caixa-amoras", label = "Box of blackberries", weight = 0.5, unique = false, usable = false, type = 'item_standard'},
	["graos-cafe"] = {name = "graos-cafe", label = "Coffee beans", weight = 0.1, unique = false, usable = false, type = 'item_standard'},
	["egg"] = {name = "egg", label = "Egg", weight = 0.1, unique = false, usable = false, type = 'item_standard'},
	-- ["pastel-frango"] = {name = "pastel-frango", label = "Pastel de frango", weight = 20, unique = false, usable = false, type = 'item_standard'},
	["muffin-chocolate"] = {name = "muffin-chocolate", label = "Chocolate muffins", weight = 0.2, unique = false, usable = false, type = 'item_standard'},
	["cup"] = {name = "cup", label = "Cup", weight = 0.5, unique = false, usable = false, type = 'item_standard'},
	["tea-leaf"] = {name = "tea-leaf", label = "Tea Leaf", weight = 1, unique = false, usable = false, type = 'item_standard'},
	["boba"] = {name = "boba", label = "Boba", weight = 1, unique = false, usable = false, type = 'item_standard'},
	["boiling_water"] = {name = "boiling_water", label = "Boiling water", weight = 0.4, unique = false, usable = false, type = 'item_standard'},
	--itemUwUCafe--Usable
	["cafe-uwu"] = {name = "cafe-uwu", label = "Café", weight = 0.4, unique = false, usable = true, type = 'item_standard'},
	["latte-uwu"] = {name = "latte-uwu", label = "Latte", weight = 0.4, unique = false, usable = true, type = 'item_standard'},
	["bubble-amora"] = {name = "bubble-amora", label = "Blackberry Bubble Tea", weight = 0.4, unique = false, usable = true, type = 'item_standard'},
	["bubble-morango"] = {name = "bubble-morango", label = "Strawberry bubble tea", weight = 0.4, unique = false, usable = true, type = 'item_standard'},
	["bubble-menta"] = {name = "bubble-menta", label = "Mint Bubble Tea", weight =0.3, unique = false, usable = true, type = 'item_standard'},
	["milkshake-chocolate"] = {name = "milkshake-chocolate", label = "Chocolate milkshake", weight = 1, unique = false, usable = true, type = 'item_standard'},
	["milkshake-morango"] = {name = "milkshake-morango", label = "Strawberry milkshake", weight = 1, unique = false, usable = true, type = 'item_standard'},
	["mocha-uwu"] = {name = "Mocha-uwu", label = "Mocha", weight = 0.4, unique = false, usable = true, type = 'item_standard'},
	["Cappuccino-uwu"] = {name = "Cappuccino-uwu", label = "Cappuccino", weight = 0.4, unique = false, usable = true, type = 'item_standard'},
	["panqueca-oreo"] = {name = "panqueca-oreo", label = "Oreo pancake", weight = 0.3, unique = false, usable = true, type = 'item_standard'},
	["waffle-nutela"] = {name = "waffle-nutela", label = "Nutella Waffle", weight = 0.3, unique = false, usable = true, type = 'item_standard'},
	["panqueca-nutela"] = {name = "panqueca-nutela", label = "Nutella pancake", weight = 0.3, unique = false, usable = true, type = 'item_standard'},
	["cupcake-morango"] = {name = "cupcake-morango", label = "Strawberry cupcake", weight = 0.2, unique = false, usable = true, type = 'item_standard'},
	["cupcake-chocolate"] = {name = "cupcake-chocolate", label = "Chocolate Cupcake", weight = 0.2, unique = false, usable = true, type = 'item_standard'},
	["cupcake-limao"] = {name = "cupcake-limao", label = "Lemon Cupcake", weight = 0.2, unique = false, usable = true, type = 'item_standard'},
	["gelado-morango"] = {name = "gelado-morango", label = "Strawberry icecream", weight = 0.2, unique = false, usable = true, type = 'item_standard'},
	["gelado-chocolate"] = {name = "gelado-chocolate", label = "Chocolate ice cream", weight = 0.2, unique = false, usable = true, type = 'item_standard'},
	["gelado-baunilha"] = {name = "gelado-baunilha", label = "Vanilla ice cream", weight = 0.2, unique = false, usable = true, type = 'item_standard'},
}