Config = {}

Config.RestrictedChannels = {
    [911] = {
        police = true,
        sheriff = true,
        ambulance = true,
        goverment = true,
        fib = true,
        marshal = true,
    },
    [911.1] = {
        police = true,
        sheriff = true,
        ambulance = true,
        goverment = true,
        fib = true,
        marshal = true,
    },
    [911.2] = {
        police = true,
        sheriff = true,
        ambulance = true,
        goverment = true,
        fib = true,
        marshal = true,
    },
    [911.3] = {
        police = true,
        sheriff = true,
        ambulance = true,
        goverment = true,
        fib = true,
        marshal = true,
    },
    [911.4] = {
        police = true,
        sheriff = true,
        ambulance = true,
        goverment = true,
        fib = true,
        marshal = true,
    },
    [911.5] = {
        police = true,
        sheriff = true,
        ambulance = true,
        goverment = true,
        fib = true,
        marshal = true,
    },
    [911.6] = {
        police = true,
        sheriff = true,
        ambulance = true,
        goverment = true,
        fib = true,
        marshal = true,
    },
    [911.7] = {
        police = true,
        sheriff = true,
        ambulance = true,
        goverment = true,
        fib = true,
        marshal = true,
    },
    [911.8] = {
        police = true,
        sheriff = true,
        ambulance = true,
        goverment = true,
        fib = true,
        marshal = true,
    },
    [985] = {
        police = true,
        sheriff = true,
        ambulance = true,
        goverment = true,
        fib = true,
        marshal = true,
    },
    [985.1] = {
        police = true,
        sheriff = true,
        ambulance = true,
        goverment = true,
        fib = true,
        marshal = true,
    },
    [985.2] = {
        police = true,
        sheriff = true,
        ambulance = true,
        goverment = true,
        fib = true,
        marshal = true,
    },
    [985.3] = {
        police = true,
        sheriff = true,
        ambulance = true,
        goverment = true,
        fib = true,
        marshal = true,
    },
    [985.4] = {
        police = true,
        sheriff = true,
        ambulance = true,
        goverment = true,
        fib = true,
        marshal = true,
    },
    [802] = {
        police = true,
        sheriff = true,
        ambulance = true,
        goverment = true,
        fib = true,
        marshal = true,
    },
    [802.1] = {
        police = true,
        sheriff = true,
        ambulance = true,
        goverment = true,
        fib = true,
        marshal = true,
    },
    [802.2] = {
        police = true,
        sheriff = true,
        ambulance = true,
        goverment = true,
        fib = true,
        marshal = true,
    },
    [802.3] = {
        police = true,
        sheriff = true,
        ambulance = true,
        goverment = true,
        fib = true,
        marshal = true,
    },
    [802.4] = {
        police = true,
        sheriff = true,
        ambulance = true,
        goverment = true,
        fib = true,
        marshal = true,
    },
    [802.5] = {
        police = true,
        sheriff = true,
        ambulance = true,
        goverment = true,
        fib = true,
        marshal = true,
    },
    [802.6] = {
        police = true,
        sheriff = true,
        ambulance = true,
        goverment = true,
        fib = true,
        marshal = true,
    },
    [802.7] = {
        police = true,
        sheriff = true,
        ambulance = true,
        goverment = true,
        fib = true,
        marshal = true,
    },
    [802.8] = {
        police = true,
        sheriff = true,
        ambulance = true,
        goverment = true,
        fib = true,
        marshal = true,
    },
    [844] = {
        police = true,
        sheriff = true,
        ambulance = true,
        goverment = true,
        fib = true,
        marshal = true,
    },
    [844.1] = {
        police = true,
        sheriff = true,
        ambulance = true,
        goverment = true,
        fib = true,
        marshal = true,
    },
    [844.2] = {
        police = true,
        sheriff = true,
        ambulance = true,
        goverment = true,
        fib = true,
        marshal = true,
    },
    [844.3] = {
        police = true,
        sheriff = true,
        ambulance = true,
        goverment = true,
        fib = true,
        marshal = true,
    },
    [844.4] = {
        police = true,
        sheriff = true,
        ambulance = true,
        goverment = true,
        fib = true,
        marshal = true,
    },
    [800] = {
        police = true,
        sheriff = true,
        ambulance = true,
        goverment = true,
        fib = true,
        marshal = true,
    },
    [800.1] = {
        police = true,
        sheriff = true,
        ambulance = true,
        goverment = true,
        fib = true,
        marshal = true,
    },
    [800.2] = {
        police = true,
        sheriff = true,
        ambulance = true,
        goverment = true,
        fib = true,
        marshal = true,
    },
    [800.3] = {
        police = true,
        sheriff = true,
        ambulance = true,
        goverment = true,
        fib = true,
        marshal = true,
    },
    [800.4] = {
        police = true,
        sheriff = true,
        ambulance = true,
        goverment = true,
        fib = true,
        marshal = true,
    },
    [801] = {
        police = true,
        sheriff = true,
        ambulance = true,
        goverment = true,
        fib = true,
        marshal = true,
    },
    [801.1] = {
        police = true,
        sheriff = true,
        ambulance = true,
        goverment = true,
        fib = true,
        marshal = true,
    },
    [801.2] = {
        police = true,
        sheriff = true,
        ambulance = true,
        goverment = true,
        fib = true,
        marshal = true,
    },
    [801.3] = {
        police = true,
        sheriff = true,
        ambulance = true,
        goverment = true,
        fib = true,
        marshal = true,
    },
    [801.4] = {
        police = true,
        sheriff = true,
        ambulance = true,
        goverment = true,
        fib = true,
        marshal = true,
    },
}

Config.MaxFrequency = 1000

Config.messages = {
    ["not_on_radio"] = "Shoma Be in Signal Vasl Nistid",
    ["on_radio"] = "Shoma Ghablan be in Signal Vasl Shodeiid.",
    ["joined_to_radio"] = "Shoma Motasel hastid be: ",
    ["restricted_channel_error"] = "Shoma Nemitavanid be in Signal motasel shavid!",
    ["invalid_radio"] = "In frequency Dar Dastres Nist!",
    ["you_on_radio"] = "Shoma Ghablan Be in Channel Motasel Bodid!",
    ["you_leave"] = "Shoma az In Channel Left Dadid",
    ['volume_radio'] = 'volume Jadid ',
    ['decrease_radio_volume'] = 'Radio Az Ghabl Roye Hade Aksar Set Shode Ast.',
    ['increase_radio_volume'] = 'Radio Az Ghabl Roye Kamtarin Mizane Seda Tanzim Shode Ast.',
    ['increase_decrease_radio_channel'] = 'channel Jadid ',
}